name: "Continuous Integration"

on:
  pull_request:
    branches:
      - main

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4

      - name: 🔍 Install dependencies
        run: pnpm install

  eslint:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v3
      - name: 🔎 Run ESLint
        run: pnpm run eslint

  build:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v3
      - name: 🛠 Build
        run: pnpm run build

  docs:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      - uses: pnpm/action-setup@v3
      - name: 🛠 Build docs
        run: pnpm run build:docs
